### PR TITLE
Added para symbol 

### PR DESCRIPTION
**Pull request by 547y4m**

### CODE REVIEW

**Review by DenverCoder1 — CHANGES_REQUESTED** [review]
Thanks!

Make sure to retain tabs in the file. The shortcuts won't work in Gboard if they are formatted wrong.

On line 615, there are spaces instead of tabs, it should be:

```
\mathbbi	𝕚	
```

On line 859, there should also be tabs instead of spaces and also a tab at the end:

```
\para	¶	
```

One more note:

The shortcut is generally defined as `\P` or `\par`. Could you add these as shortcuts (on separate lines) instead of `\para`?

These changes can be pushed to this same branch. If you have any questions, let me know.

**Comment by 547y4m** [comment]
@DenverCoder1 how do I add tabs & of what length? Can u please elaborate

**Comment by 547y4m** [comment]
@DenverCoder1 i added the tabs please check it.

**Comment by 547y4m** [comment]
@DenverCoder1 Please label as "hacktoberfest-accepted" and merge it. It's my first haktober 😄

**Review by DenverCoder1 — APPROVED** [review]
@547y4m Tabs look great!

**Comment by DenverCoder1** [comment]
👍 Happy Hacktoberfest! Merged!

**Pull request merged**
