### PR TITLE
feat: Added swastika and revSwastika

### PR DESCRIPTION
**Pull request by Anshul-13J**
Added swastika and reverse swastika sign (not available on google keyboard)

### CODE REVIEW

**Review by DenverCoder1 — APPROVED** [review]
I'm a bit reluctant on this one due to Nazi appropriation of the symbol, but I can see there could be positive uses of it in some cultures.

**Comment by DenverCoder1** [comment]
Thanks for the contribution :tada:

**Comment by Anshul-13J** [comment]
> I'm a bit reluctant on this one due to Nazi appropriation of the symbol, but I can see there could be positive uses of it in some cultures.

This is a holy symbol in Indian Culture, although it is quite similar to the Nazi one.
Nazi symbol is quite tilted also.

Also, can I get Hacktoberfest accepted tag?

**Comment by DenverCoder1** [comment]
Since the repo has the `hacktoberfest` topic, all merged pull requests should count automatically.

If it says on the site "waiting" with about 7 days remaining, then it should be good to go. :+1: 

If it shows as something else, let me know.

**Pull request merged**
