### PR TITLE
Added Triangles symbol

### PR DESCRIPTION
**Pull request by 547y4m**
@DenverCoder1 please merge it as another "hacktoberfest-accepted" label. 😄

### CODE REVIEW

**Comment by DenverCoder1** [comment]
There are more types of triangles that could be added

Using the `stix` package, these are the shortcuts for the 4 you added:

image

Non-"black" versions exist as well

image

There's a whole list here with symbols that can be copied. http://mirrors.ibiblio.org/CTAN/fonts/stix/doc/stix.pdf

**Comment by 547y4m** [comment]
Okay, at least merge till this i will be adding more, after my exams.

**Comment by DenverCoder1** [comment]
For the black triangles, the shortcuts should be

```
\lrblacktriangle
\llblacktriangle
\ulblacktriangle
\urblacktriangle
```

**Comment by 547y4m** [comment]
okay correcting it.

**Comment by 547y4m** [comment]
@DenverCoder1 corrected. 😃

**Comment by DenverCoder1** [comment]
Thanks!

**Pull request merged**
