### PR TITLE
Add playing card suits

### PR DESCRIPTION
**Pull request by elshaek**
Issue #5

### CODE REVIEW

**Comment by DenverCoder1** [comment]
Hi, this is a great addition! 👍

I tried downloading your fork, but the new symbols didn't get imported. I think the formatting might be a bit off. Can you make sure that between the shortcut and the symbol there is a tab character and at the end of each line there is a tab character? Having spaces which are the same length won't work. You can copy the tabs from other lines if the editor you use makes it difficult.

**Comment by elshaek** [comment]
Hi, I've changed the spaces to tabs and tried importing it. Please let me know if it still is not working. 
And thanks for creating this issue so first-timers like me can take baby steps in contributing to open source projects!

**Comment by DenverCoder1** [comment]
👍 Great! It is working now.

I see that the file ".vscode/settings.json" was added to the last commit. Could we remove that and then I'll merge the request?

**Comment by elshaek** [comment]
sorry about that, done!

**Comment by DenverCoder1** [comment]
Thanks!

**Pull request merged**
